AWSTemplateFormatVersion: '2010-09-09'
Description: AppSync Lambda Resolvers
Outputs:
  ProdDataEndpoint:
    Description: API Prod stage endpoint
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
Parameters:
  IAMUsername:
    Default: sysadmin
    Description: Username of the IAM user for this service
    Type: String
Resources:
  Lambda:
    Properties:
      CodeUri: s3://gdps-fs-sum-dwnld/lambda/11b281ab6263c1113c2cc698484dcdec
      Environment:
        Variables:
          Stage: prod
      Events:
        Create:
          Properties:
            Method: post
            Path: /report
          Type: Api
        Ping:
          Properties:
            Method: get
            Path: /report
          Type: Api
      Handler: /report
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: go1.x
      Tags:
        BillTo: Gales
      Timeout: 10
    Type: AWS::Serverless::Function
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/gdps-fs-sum-dwnld*
          Version: '2012-10-17'
        PolicyName: FunctionParameterAccess
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: FunctionLogAccess
      - PolicyDocument:
          Statement:
          - Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: FunctionXRayAccess
      - PolicyDocument:
          Statement:
          - Action:
            - s3:*
            Effect: Allow
            Resource: arn:aws:s3:::gdps-fs-sum-dwnld/reports/*
          Version: '2012-10-17'
        PolicyName: FunctionS3Access
    Type: AWS::IAM::Role
  ServerlessRestApi:
    DeletionPolicy: Retain
    Properties:
      StageName: Prod
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
